# Generated by Django 3.1 on 2020-08-11 20:43

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2020)])),
                ('Dhero', models.CharField(max_length=150)),
            ],
        ),
    ]
