# Generated by Django 3.1 on 2020-08-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Movie',
        ),
    ]
